baseurl = "https://vicholp.github.io/blog/"
languageCode = "es-cl"
defaultContentLanguage = "es"
theme = "hello-friend"
paginate = 10

[languages]
  [languages.es]
    title = "Vicente Lineros Blog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Ver mas"
    writtenBy = "Escrito por"
    readMore = "Leer mas"
    readOtherPosts = "Read other posts"
    newerPosts = "Nuevos posts"
    olderPosts = "Posts antiguos"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.es.params.logo]
      logoText = "Vicente Lineros"
      logoHomeLink = "/blog"
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

