baseurl = "https://vicholp.github.io/vicho.dev-blog/"
languageCode = "es-cl"
theme = "hello-friend"
paginate = 10

[languages]
  [languages.es]
    title = "Vicente Lineros Blog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Ver mas"
    writtenBy = "Escrito por"
    readMore = "Leer mas"
    readOtherPosts = "Read other posts"
    newerPosts = "Nuevos posts"
    olderPosts = "Posts antiguos"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "hello friend"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

